cmake_minimum_required(VERSION 3.3)

set(LZX_HARDWARE_VERSION ${PROJECT_VERSION})

set(AHK_SCRIPTS_DIR "C:/Users/Lars larsen/lzxparts/scripts/autohotkey")
#include(${AHK_SCRIPTS_DIR}/CMakeLists.txt)

project(${LZX_PROJECT_NAME} VERSION 0)

set(CPACK_GENERATOR "ZIP")
set(CPACK_PACKAGE_FILE_NAME ${LZX_PROJECT_NAME}-${LZX_HARDWARE_VERSION})

set(LZX_FILE_PREFIX ${LZX_PROJECT_NAME}-${LZX_HARDWARE_VERSION}-)


file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR}/${LZX_FILE_PREFIX}top-silk.gbr TMP_PATH)
set(GERBER_FILES ${TMP_PATH} ${GERBER_FILES})
file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR}/${LZX_FILE_PREFIX}top-mask.gbr TMP_PATH)
set(GERBER_FILES ${TMP_PATH} ${GERBER_FILES})
file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR}/${LZX_FILE_PREFIX}top-paste.gbr TMP_PATH)
set(GERBER_FILES ${TMP_PATH} ${GERBER_FILES})
file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR}/${LZX_FILE_PREFIX}layer-1-top.gbr TMP_PATH)
set(GERBER_FILES ${TMP_PATH} ${GERBER_FILES})
file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR}/${LZX_FILE_PREFIX}layer-2-bottom.gbr TMP_PATH)
set(GERBER_FILES ${TMP_PATH} ${GERBER_FILES})
file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR}/${LZX_FILE_PREFIX}bottom-paste.gbr TMP_PATH)
set(GERBER_FILES ${TMP_PATH} ${GERBER_FILES})
file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR}/${LZX_FILE_PREFIX}bottom-mask.gbr TMP_PATH)
set(GERBER_FILES ${TMP_PATH} ${GERBER_FILES})
file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR}/${LZX_FILE_PREFIX}bottom-silk.gbr TMP_PATH)
set(GERBER_FILES ${TMP_PATH} ${GERBER_FILES})
file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR}/${LZX_FILE_PREFIX}board-outline.gbr TMP_PATH)
set(GERBER_FILES ${TMP_PATH} ${GERBER_FILES})
file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR}/${LZX_FILE_PREFIX}nc-drill.drl TMP_PATH)
set(GERBER_FILES ${TMP_PATH} ${GERBER_FILES})
file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR}/${LZX_FILE_PREFIX}xy-placement-data.csv TMP_PATH)
set(GERBER_FILES ${TMP_PATH} ${GERBER_FILES})

file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR}/kicad/bom/${LZX_FILE_PREFIX}ibom.html TMP_PATH)
set(BOM_FILES ${TMP_PATH} ${BOM_FILES})
file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR}/${LZX_FILE_PREFIX}bom.csv TMP_PATH)
set(BOM_FILES ${TMP_PATH} ${BOM_FILES})

# file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR}/${LZX_FILE_PREFIX}model3d.stp TMP_PATH)
# set(3D_FILES ${TMP_PATH} ${3D_FILES})


set(CMAKE_VERBOSE_MAKEFILE ON)
set(CMAKE_COLOR_MAKEFILE   ON)

add_custom_target(GerberExport ALL 
    DEPENDS ${GERBER_FILES} 
)
#add_dependencies(GerberExport ScriptExport)

add_custom_target(BomExport ALL 
    DEPENDS ${BOM_FILES} 
)
add_dependencies(BomExport GerberExport)

file(TO_NATIVE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/${LZX_PROJECT_NAME}.dip PCB_FILE_PATH)
file(TO_NATIVE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/${LZX_PROJECT_NAME}.dch SCH_FILE_PATH)
file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR} BINARY_FILE_PATH)
file(TO_NATIVE_PATH ${CMAKE_CURRENT_SOURCE_DIR} SOURCE_FILE_PATH)

file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR}/kicad/${LZX_PROJECT_NAME}-${LZX_HARDWARE_VERSION}.kicad_pcb KICAD_FILE_PATH)
file(TO_NATIVE_PATH "C:/Users/Lars larsen/AppData/Roaming/kicad/scripting/plugins/InteractiveHtmlBom/generate_interactive_bom.py" IBOM_FILE_PATH)

file(TO_NATIVE_PATH "C:/Program Files/KiCad/bin/python.exe" KICAD_PROG_FILE_PATH)


add_custom_command(OUTPUT ${GERBER_FILES}
    COMMAND export-pcb-2layers.exe ${PCB_FILE_PATH} ${SCH_FILE_PATH} ${BINARY_FILE_PATH} ${LZX_PROJECT_NAME} ${LZX_HARDWARE_VERSION} ${SOURCE_FILE_PATH}
    WORKING_DIRECTORY ${AHK_SCRIPTS_DIR}
)
install(FILES ${GERBER_FILES} DESTINATION "${LZX_PROJECT_NAME}/gerbers")
#install(FILES ${3D_FILES} DESTINATION "${LZX_PROJECT_NAME}/model3d")

add_custom_command(OUTPUT ${BOM_FILES}
    COMMAND ${KICAD_PROG_FILE_PATH} ${IBOM_FILE_PATH} --no-browser --name-format ${LZX_FILE_PREFIX}ibom ${KICAD_FILE_PATH}
    WORKING_DIRECTORY ${CURRENT_BINARY_DIR}
)

install(FILES ${BOM_FILES} DESTINATION "${LZX_PROJECT_NAME}/bom")


set(CPACK_GENERATOR "ZIP")
include(CPack)
# set(LZX_CMAKE_SCRIPTS_DIR ${CMAKE_CURRENT_SOURCE_DIR}/cmake/modules)
# set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${LZX_CMAKE_SCRIPTS_DIR})

# include(LZXMakeVersion)

#Ahk2Exe.exe /in MyScript.ahk [/out MyScript.exe] [/icon MyIcon.ico] [/bin AutoHotkeySC.bin] [/mpress 0or1]


# project(${LZX_PROJECT_NAME} VERSION 0)
# include(CPack)
# set(CPACK_GENERATOR "ZIP")
# set(CPACK_PACKAGE_FILE_NAME ${LZX_PROJECT_NAME}-${LZX_HARDWARE_VERSION}-RS274X)
