cmake_minimum_required(VERSION 3.3)


add_subdirectory(${CMAKE_SOURCE_DIR}/lzxparts/scripts/autohotkey)

set(LZX_HARDWARE_VERSION ${PROJECT_VERSION})
set(AHK_SCRIPTS_DIR ${CMAKE_CURRENT_SOURCE_DIR}/lzxparts/scripts/autohotkey)
project(${LZX_PROJECT_NAME} VERSION 0)

set(CPACK_GENERATOR "ZIP")
set(CPACK_PACKAGE_FILE_NAME ${LZX_PROJECT_NAME}-${LZX_HARDWARE_VERSION})

set(LZX_FILE_PREFIX ${LZX_PROJECT_NAME}-${LZX_HARDWARE_VERSION}-)

file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR}/${LZX_FILE_PREFIX}top-silk.gbr TMP_PATH)
set(GERBER_FILES ${TMP_PATH} ${GERBER_FILES})
file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR}/${LZX_FILE_PREFIX}top-mask.gbr TMP_PATH)
set(GERBER_FILES ${TMP_PATH} ${GERBER_FILES})
file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR}/${LZX_FILE_PREFIX}top-paste.gbr TMP_PATH)
set(GERBER_FILES ${TMP_PATH} ${GERBER_FILES})
file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR}/${LZX_FILE_PREFIX}layer-1-top.gbr TMP_PATH)
set(GERBER_FILES ${TMP_PATH} ${GERBER_FILES})
file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR}/${LZX_FILE_PREFIX}layer-2.gbr TMP_PATH)
set(GERBER_FILES ${TMP_PATH} ${GERBER_FILES})
file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR}/${LZX_FILE_PREFIX}layer-3.gbr TMP_PATH)
set(GERBER_FILES ${TMP_PATH} ${GERBER_FILES})
file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR}/${LZX_FILE_PREFIX}layer-4.gbr TMP_PATH)
set(GERBER_FILES ${TMP_PATH} ${GERBER_FILES})
file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR}/${LZX_FILE_PREFIX}layer-5.gbr TMP_PATH)
set(GERBER_FILES ${TMP_PATH} ${GERBER_FILES})
file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR}/${LZX_FILE_PREFIX}layer-6-bottom.gbr TMP_PATH)
set(GERBER_FILES ${TMP_PATH} ${GERBER_FILES})
file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR}/${LZX_FILE_PREFIX}bottom-paste.gbr TMP_PATH)
set(GERBER_FILES ${TMP_PATH} ${GERBER_FILES})
file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR}/${LZX_FILE_PREFIX}bottom-mask.gbr TMP_PATH)
set(GERBER_FILES ${TMP_PATH} ${GERBER_FILES})
file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR}/${LZX_FILE_PREFIX}bottom-silk.gbr TMP_PATH)
set(GERBER_FILES ${TMP_PATH} ${GERBER_FILES})
file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR}/${LZX_FILE_PREFIX}board-outline.gbr TMP_PATH)
set(GERBER_FILES ${TMP_PATH} ${GERBER_FILES})
file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR}/${LZX_FILE_PREFIX}nc-drill.drl TMP_PATH)
set(GERBER_FILES ${TMP_PATH} ${GERBER_FILES})
file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR}/${LZX_FILE_PREFIX}xy-placement-data.csv TMP_PATH)
set(GERBER_FILES ${TMP_PATH} ${GERBER_FILES})
file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR}/${LZX_FILE_PREFIX}xy-placement-data.csv TMP_PATH)
set(GERBER_FILES ${TMP_PATH} ${GERBER_FILES})
file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR}/${LZX_PROJECT_NAME}-documentation.pdf TMP_PATH)
set(GERBER_FILES ${TMP_PATH} ${GERBER_FILES})


set(CMAKE_VERBOSE_MAKEFILE ON)
set(CMAKE_COLOR_MAKEFILE   ON)


add_custom_target(GerberExport ALL 
    DEPENDS ${GERBER_FILES} 
)
add_dependencies(GerberExport ScriptExport)

file(TO_NATIVE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/${LZX_PROJECT_NAME}.dip PCB_FILE_PATH)
file(TO_NATIVE_PATH ${CMAKE_CURRENT_BINARY_DIR} BINARY_FILE_PATH)

file(TO_NATIVE_PATH ${AHK_SCRIPTS_DIR} FIXED_SCRIPTS_DIR)

add_custom_command(OUTPUT ${GERBER_FILES}  
    COMMAND export-pcb-6layers.exe ${PCB_FILE_PATH} ${BINARY_FILE_PATH} ${LZX_PROJECT_NAME} ${LZX_HARDWARE_VERSION} 
    WORKING_DIRECTORY ${FIXED_SCRIPTS_DIR}
)
install(FILES ${GERBER_FILES} DESTINATION "Gerbers")

set(CPACK_GENERATOR "ZIP")
include(CPack)
# set(LZX_CMAKE_SCRIPTS_DIR ${CMAKE_CURRENT_SOURCE_DIR}/cmake/modules)
# set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${LZX_CMAKE_SCRIPTS_DIR})

# include(LZXMakeVersion)

#Ahk2Exe.exe /in MyScript.ahk [/out MyScript.exe] [/icon MyIcon.ico] [/bin AutoHotkeySC.bin] [/mpress 0or1]


# project(${LZX_PROJECT_NAME} VERSION 0)
# include(CPack)
# set(CPACK_GENERATOR "ZIP")
# set(CPACK_PACKAGE_FILE_NAME ${LZX_PROJECT_NAME}-${LZX_HARDWARE_VERSION}-RS274X)
